# Change these first
owner: vivesvoies # Your GitHub organization or username, where this repository lives
repo: court-message-uptime # The name of this repository

sites:
  - name: Court-message (production)
    url: https://court-message.fr
  - name: Court-message (staging)
    url: https://alpha.court-message.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /court-message-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Court-message
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime for the main and staging Court-message instances on Scalingo.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
workflowSchedule:
  graphs: "13 0 * * *"
  responseTime: "11 23 * * *"
  staticSite: "3 1 * * *"
  summary: "4 0 * * *"
  updateTemplate: "6 0 * * *"
  updates: "1 3 * * *"
  uptime: "2-59/5 * * * *"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
